development:
  protocol: 'http'
  host: 'localhost'
  port: 8529
  password: ''
  username: ''
  database: 'github_recommender_development'

test:
  protocol: 'http'
  host: 'localhost'
  port: 8529
  password: ''
  username: ''
  database: 'github_recommender_test'

production:
  protocol: 'http'
  host: '<%= ENV['ARANGODB_PORT_8529_TCP_ADDR'] %>'
  port: '<%= ENV['ARANGODB_PORT_8529_TCP_PORT'] %>'
  password: ''
  username: ''
  database: '_system'
